package com.example.pein.demo.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.pein.demo.dao.STORY;
import com.example.pein.demo.dao.NEWS;

import com.example.pein.demo.dao.STORYDao;
import com.example.pein.demo.dao.NEWSDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sTORYDaoConfig;
    private final DaoConfig nEWSDaoConfig;

    private final STORYDao sTORYDao;
    private final NEWSDao nEWSDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sTORYDaoConfig = daoConfigMap.get(STORYDao.class).clone();
        sTORYDaoConfig.initIdentityScope(type);

        nEWSDaoConfig = daoConfigMap.get(NEWSDao.class).clone();
        nEWSDaoConfig.initIdentityScope(type);

        sTORYDao = new STORYDao(sTORYDaoConfig, this);
        nEWSDao = new NEWSDao(nEWSDaoConfig, this);

        registerDao(STORY.class, sTORYDao);
        registerDao(NEWS.class, nEWSDao);
    }
    
    public void clear() {
        sTORYDaoConfig.getIdentityScope().clear();
        nEWSDaoConfig.getIdentityScope().clear();
    }

    public STORYDao getSTORYDao() {
        return sTORYDao;
    }

    public NEWSDao getNEWSDao() {
        return nEWSDao;
    }

}
